injector:
  enabled: false

server:
  image:
    repository: "hashicorp/vault"
    tag: "1.9.2"
    pullPolicy: IfNotPresent
  logLevel: "info"
  logFormat: "json"
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 256Mi
      cpu: 250m
#   priorityClassName: "medium-priority" # если они определены в кластере

  dataStorage:
    enabled: false
  dev:
    enabled: false
  standalone:
    enabled: false
  ha:
    enabled: true
    replicas: 2
    apiAddr: null

    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }

      storage "consul" {
       path = "vault/"
       address = "HOST_IP:8500"
      }

      service_registration "kubernetes" {}

csi:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 50m
      memory: 128Mi